In [1]:
#advance indexing
import numpy as np

a=np.array([1,2,3,4,5,6])
idx=np.array([1,3,5])
print(a[idx])
c=a>3
print(a[c])


[2 4 6]
[4 5 6]


In [2]:
#sorting
import numpy as np

dtype=[('name','S10'),('year',int),('cgpa',float)]

val=[('Snehal',2005,9.6),
     ('Krishiv',2005,6.5),
     ('Richa',2004,7.6)]

a=np.array(val,dtype=dtype)

print(np.sort(a,order='name'))
print(np.sort(a,order=['year','cgpa']))

#s10 is used for storing  the string values
#it is provide the faster access of array than strng
#if name is longer than 10 character then it will cut off first 10 char


[(b'Krishiv', 2005, 6.5) (b'Richa', 2004, 7.6) (b'Snehal', 2005, 9.6)]
[(b'Richa', 2004, 7.6) (b'Krishiv', 2005, 6.5) (b'Snehal', 2005, 9.6)]


In [3]:
#row slicing
import numpy as np

a=np.array([[1,2,3],
            [4,5,6]])

print(a[1:4])
print(a[:,1])


[[4 5 6]]
[2 5]


In [4]:
#resize
import numpy as np
arr=np.array([1,2,3,4,5,6])
newArray=np.resize(arr,(3,4))
print(newArray)


[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


In [11]:
#reshape
import numpy as np

a1=np.array([12,43,34,23,45,56])
r=a1.reshape(2,3)
print(r)

a2=np.array([45,34,23,45,65,45,34,54])
r=a2.reshape(2,2,2)
print(r)

r=a2.reshape(4,-1)
print(r)


[[12 43 34]
 [23 45 56]]
[[[45 34]
  [23 45]]

 [[65 45]
  [34 54]]]
[[45 34]
 [23 45]
 [65 45]
 [34 54]]


In [6]:
import numpy as np

a1=np.array([1,2,3])
a2=np.array([[1,2],[3,4]])
a3=np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(a1)
print(a2)
print(a3)


[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [7]:
#numpy functions
import numpy as np

a1=np.zeros((3,3))
a2=np.zeros((2,2))
a3=np.arange(0,10,3)
a4=np.ones((2,2))

print(a1)
print(a2)
print(a3)
print(a4)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]]
[0 3 6 9]
[[1. 1.]
 [1. 1.]]


In [8]:
#array indexing
import numpy as np

a1=np.array([10,20,30,40,50])

print(a1[1])
print(a1[-4])

a2=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a2[0,2])


20
20
3


In [9]:
#arithmatic operations
import numpy as np

x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)
print(x-y)
print(x*y)
print(x/y)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
#stacking in array
import numpy as np

a1=np.array([12,32,12])
a2=np.array([67,54,43])
np.stack((a1,a2),axis=1)

a3=np.array([1,2,3])
a4=np.array([4,5,6])

np.hstack((a3,a4))
np.vstack((a3,a4))


array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
#splitting array

import numpy as np
arr=np.array([1,2,3,4,6])
res=np.array_split(arr,3)
print(res)

#allows un-even splitting

[array([1, 2]), array([3, 4]), array([6])]


In [7]:
import numpy as np
arr=np.arange(6)
res=np.split(arr,3)
print(res)

#the values of the sub-division must be equaly divide

[array([0, 1]), array([2, 3]), array([4, 5])]


In [12]:
import numpy as np
arr=np.array([[1,2,3],[5,4,5],[6,5,4],[8,7,6]])
print(arr)
res=np.vsplit(arr,2)
print(res)

#the division must be equal in verticle split

[[1 2 3]
 [5 4 5]
 [6 5 4]
 [8 7 6]]
[array([[1, 2, 3],
       [5, 4, 5]]), array([[6, 5, 4],
       [8, 7, 6]])]


In [16]:
import numpy as np
arr=np.array([[1,2,3],[5,4,5],[6,5,4],[8,7,6]])
res=np.hsplit(arr,3)
print(res)

[array([[1],
       [5],
       [6],
       [8]]), array([[2],
       [4],
       [5],
       [7]]), array([[3],
       [5],
       [4],
       [6]])]


In [22]:
#broadcasting

import numpy as np

arr=np.array([[12,3,4],[45,34,54],[65,45,65]])
a=10
res=arr+a
print(res)

a1=np.array([45,34,54])
a2=np.array([[56,45,65],[67,45,34]])
res=a1+a2
print(res)

[[22 13 14]
 [55 44 64]
 [75 55 75]]
[[101  79 119]
 [123  90  99]]
